from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument('mission_sequence', default_value='laptop'),
        DeclareLaunchArgument('return_home', default_value='true'),
        DeclareLaunchArgument('target_class', default_value=''),
        DeclareLaunchArgument('use_ocr_next_target', default_value='true'),
        DeclareLaunchArgument('ocr_timeout_sec', default_value='8.0'),
        DeclareLaunchArgument('home_marker_ocr_timeout_sec', default_value='10.0'),
        DeclareLaunchArgument('max_mission_targets', default_value='10'),
        DeclareLaunchArgument('allowed_target_classes', default_value='chair,laptop,backpack'),
        DeclareLaunchArgument('label_aliases', default_value='suitcase:backpack,handbag:backpack,couch:chair,dining table:chair'),
        DeclareLaunchArgument('require_scan_for_motion', default_value='false'),
        DeclareLaunchArgument('initial_forward_sec', default_value='0.0'),
        DeclareLaunchArgument('initial_forward_speed', default_value='0.12'),
        DeclareLaunchArgument('initial_emergency_stop_distance', default_value='0.10'),
        DeclareLaunchArgument('initial_spin_360_sec', default_value='18.0'),

        DeclareLaunchArgument('model_path', default_value='models/yolov8s.pt'),
        DeclareLaunchArgument('image_topic', default_value='/image_raw'),
        DeclareLaunchArgument('scan_topic', default_value='/scan'),
        DeclareLaunchArgument('odom_topic', default_value='/odom'),
        DeclareLaunchArgument('cmd_vel_topic', default_value='/cmd_vel'),
        DeclareLaunchArgument('allow_blind_search_rotation', default_value='true'),

        DeclareLaunchArgument('confidence_threshold', default_value='0.40'),
        DeclareLaunchArgument('process_every_n_frames', default_value='3'),
        DeclareLaunchArgument('stop_distance', default_value='0.55'),
        DeclareLaunchArgument('obstacle_stop_distance', default_value='0.20'),
        DeclareLaunchArgument('front_angle_deg', default_value='18.0'),
        DeclareLaunchArgument('side_angle_min_deg', default_value='25.0'),
        DeclareLaunchArgument('side_angle_max_deg', default_value='75.0'),
        DeclareLaunchArgument('use_paper_stop', default_value='true'),
        DeclareLaunchArgument('paper_stop_area_ratio', default_value='0.045'),
        DeclareLaunchArgument('paper_center_deadband', default_value='0.28'),
        DeclareLaunchArgument('paper_angular_gain', default_value='0.18'),
        DeclareLaunchArgument('paper_forward_speed', default_value='0.08'),
        DeclareLaunchArgument('paper_search_timeout_sec', default_value='8.0'),
        DeclareLaunchArgument('max_paper_search_attempts', default_value='3'),
        DeclareLaunchArgument('max_paper_search_attempts_with_cue', default_value='5'),
        DeclareLaunchArgument('paper_reposition_sec', default_value='1.2'),
        DeclareLaunchArgument('paper_reposition_linear_speed', default_value='-0.07'),
        DeclareLaunchArgument('paper_reposition_angular_speed', default_value='0.18'),
        DeclareLaunchArgument('paper_visual_reposition_forward_speed', default_value='0.04'),
        DeclareLaunchArgument('paper_cue_min_area_ratio', default_value='0.003'),
        DeclareLaunchArgument('paper_cue_min_black_ratio', default_value='0.01'),
        DeclareLaunchArgument('paper_cue_memory_sec', default_value='2.0'),
        DeclareLaunchArgument('object_front_distance', default_value='0.85'),
        DeclareLaunchArgument('object_front_min_box_width_ratio', default_value='0.20'),
        DeclareLaunchArgument('object_close_box_width_ratio', default_value='0.42'),
        DeclareLaunchArgument('laptop_object_close_box_width_ratio', default_value='0.65'),
        DeclareLaunchArgument('paper_search_angular_speed', default_value='0.18'),

        # V6: faster + target lock.
        DeclareLaunchArgument('linear_speed', default_value='0.18'),
        DeclareLaunchArgument('min_forward_speed_when_target_found', default_value='0.15'),
        DeclareLaunchArgument('locked_blind_forward_speed', default_value='0.13'),
        DeclareLaunchArgument('angular_gain', default_value='0.10'),
        DeclareLaunchArgument('max_angular_speed', default_value='0.07'),
        DeclareLaunchArgument('center_deadband', default_value='0.35'),
        DeclareLaunchArgument('search_angular_speed', default_value='0.35'),
        DeclareLaunchArgument('turn_sign', default_value='-1.0'),
        DeclareLaunchArgument('target_memory_sec', default_value='99.0'),
        DeclareLaunchArgument('lock_on_first_detection', default_value='true'),
        DeclareLaunchArgument('arrive_hold_sec', default_value='1.5'),

        DeclareLaunchArgument('return_linear_speed', default_value='0.14'),
        DeclareLaunchArgument('return_angular_gain', default_value='1.2'),
        DeclareLaunchArgument('return_max_angular_speed', default_value='0.45'),
        DeclareLaunchArgument('return_stop_distance', default_value='0.12'),
        DeclareLaunchArgument('return_waypoint_tolerance', default_value='0.18'),
        DeclareLaunchArgument('return_heading_deadband', default_value='0.25'),
        DeclareLaunchArgument('record_path_min_distance', default_value='0.05'),
        DeclareLaunchArgument('final_turn_speed', default_value='0.35'),
        DeclareLaunchArgument('final_turn_tolerance', default_value='0.08'),

        DeclareLaunchArgument('ocr_debug_image_topic', default_value='/ocr_debug_image'),
        DeclareLaunchArgument('ocr_interval_sec', default_value='0.7'),

        Node(
            package='capstone_motion',
            executable='yolo_lidar_mission_node',
            name='yolo_lidar_mission_node',
            output='screen',
            parameters=[{
                'mission_sequence': LaunchConfiguration('mission_sequence'),
                'return_home': LaunchConfiguration('return_home'),
                'target_class': LaunchConfiguration('target_class'),
                'use_ocr_next_target': LaunchConfiguration('use_ocr_next_target'),
                'ocr_timeout_sec': LaunchConfiguration('ocr_timeout_sec'),
                'home_marker_ocr_timeout_sec': LaunchConfiguration('home_marker_ocr_timeout_sec'),
                'max_mission_targets': LaunchConfiguration('max_mission_targets'),
                'allowed_target_classes': LaunchConfiguration('allowed_target_classes'),
                'label_aliases': LaunchConfiguration('label_aliases'),
                'require_scan_for_motion': LaunchConfiguration('require_scan_for_motion'),
                'initial_forward_sec': LaunchConfiguration('initial_forward_sec'),
                'initial_forward_speed': LaunchConfiguration('initial_forward_speed'),
                'initial_emergency_stop_distance': LaunchConfiguration('initial_emergency_stop_distance'),
                'initial_spin_360_sec': LaunchConfiguration('initial_spin_360_sec'),
                'model_path': LaunchConfiguration('model_path'),
                'image_topic': LaunchConfiguration('image_topic'),
                'scan_topic': LaunchConfiguration('scan_topic'),
                'odom_topic': LaunchConfiguration('odom_topic'),
                'cmd_vel_topic': LaunchConfiguration('cmd_vel_topic'),
                'allow_blind_search_rotation': LaunchConfiguration('allow_blind_search_rotation'),
                'confidence_threshold': LaunchConfiguration('confidence_threshold'),
                'process_every_n_frames': LaunchConfiguration('process_every_n_frames'),
                'stop_distance': LaunchConfiguration('stop_distance'),
                'obstacle_stop_distance': LaunchConfiguration('obstacle_stop_distance'),
                'front_angle_deg': LaunchConfiguration('front_angle_deg'),
                'side_angle_min_deg': LaunchConfiguration('side_angle_min_deg'),
                'side_angle_max_deg': LaunchConfiguration('side_angle_max_deg'),
                'use_paper_stop': LaunchConfiguration('use_paper_stop'),
                'paper_stop_area_ratio': LaunchConfiguration('paper_stop_area_ratio'),
                'paper_center_deadband': LaunchConfiguration('paper_center_deadband'),
                'paper_angular_gain': LaunchConfiguration('paper_angular_gain'),
                'paper_forward_speed': LaunchConfiguration('paper_forward_speed'),
                'paper_search_timeout_sec': LaunchConfiguration('paper_search_timeout_sec'),
                'max_paper_search_attempts': LaunchConfiguration('max_paper_search_attempts'),
                'max_paper_search_attempts_with_cue': LaunchConfiguration('max_paper_search_attempts_with_cue'),
                'paper_reposition_sec': LaunchConfiguration('paper_reposition_sec'),
                'paper_reposition_linear_speed': LaunchConfiguration('paper_reposition_linear_speed'),
                'paper_reposition_angular_speed': LaunchConfiguration('paper_reposition_angular_speed'),
                'paper_visual_reposition_forward_speed': LaunchConfiguration('paper_visual_reposition_forward_speed'),
                'paper_cue_min_area_ratio': LaunchConfiguration('paper_cue_min_area_ratio'),
                'paper_cue_min_black_ratio': LaunchConfiguration('paper_cue_min_black_ratio'),
                'paper_cue_memory_sec': LaunchConfiguration('paper_cue_memory_sec'),
                'object_front_distance': LaunchConfiguration('object_front_distance'),
                'object_front_min_box_width_ratio': LaunchConfiguration('object_front_min_box_width_ratio'),
                'object_close_box_width_ratio': LaunchConfiguration('object_close_box_width_ratio'),
                'laptop_object_close_box_width_ratio': LaunchConfiguration('laptop_object_close_box_width_ratio'),
                'paper_search_angular_speed': LaunchConfiguration('paper_search_angular_speed'),
                'linear_speed': LaunchConfiguration('linear_speed'),
                'min_forward_speed_when_target_found': LaunchConfiguration('min_forward_speed_when_target_found'),
                'locked_blind_forward_speed': LaunchConfiguration('locked_blind_forward_speed'),
                'angular_gain': LaunchConfiguration('angular_gain'),
                'max_angular_speed': LaunchConfiguration('max_angular_speed'),
                'center_deadband': LaunchConfiguration('center_deadband'),
                'search_angular_speed': LaunchConfiguration('search_angular_speed'),
                'turn_sign': LaunchConfiguration('turn_sign'),
                'target_memory_sec': LaunchConfiguration('target_memory_sec'),
                'lock_on_first_detection': LaunchConfiguration('lock_on_first_detection'),
                'arrive_hold_sec': LaunchConfiguration('arrive_hold_sec'),
                'return_linear_speed': LaunchConfiguration('return_linear_speed'),
                'return_angular_gain': LaunchConfiguration('return_angular_gain'),
                'return_max_angular_speed': LaunchConfiguration('return_max_angular_speed'),
                'return_stop_distance': LaunchConfiguration('return_stop_distance'),
                'return_waypoint_tolerance': LaunchConfiguration('return_waypoint_tolerance'),
                'return_heading_deadband': LaunchConfiguration('return_heading_deadband'),
                'record_path_min_distance': LaunchConfiguration('record_path_min_distance'),
                'final_turn_speed': LaunchConfiguration('final_turn_speed'),
                'final_turn_tolerance': LaunchConfiguration('final_turn_tolerance'),
            }],
        ),

        Node(
            package='capstone_ocr',
            executable='ocr_reader_node',
            name='ocr_reader_node',
            output='screen',
            parameters=[{
                'image_topic': LaunchConfiguration('image_topic'),
                'debug_image_topic': LaunchConfiguration('ocr_debug_image_topic'),
                'ocr_interval_sec': LaunchConfiguration('ocr_interval_sec'),
            }],
        ),
    ])
