<?xml version="1.0"?>
<package format="3">
  <name>capstone_motion</name>
  <version>0.0.5</version>
  <description>YOLO target mission with LiDAR stop and odom return home</description>
  <maintainer email="hugim@example.com">hugim</maintainer>
  <license>MIT</license>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
